development:
  adapter: postgresql
  encoding: unicode
  database: rorschach_development
  pool: 5
  username: rorschach
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rorschach_test
  pool: 5
  username: rorschach
  password:
